version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: bugtracker_postgres
    restart: always
    environment:
      POSTGRES_USER: bugtracker_user
      POSTGRES_PASSWORD: bugtracker_password
      POSTGRES_DB: bugtracker_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: bugtracker_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@bugtracker.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
