networks:
  gateway_network:
    driver: bridge

services:
  gatewayservice:
    build: ../src/Gateway
    container_name: gatewayservice
    ports:
      - "5010:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_RUNNING_IN_CONTAINER=true
    depends_on:
      - userservice
      - projectservice
      - commentsservice
    networks:
      - gateway_network

  userservice:
    build:
      context: ../
      dockerfile: ./src/Services/UserService/Dockerfile
    container_name: userservice
    ports:
      - "5002:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Host=userdb;Database=user_db;Username=postgres;Password=postgres;
    networks:
      - gateway_network

  projectservice:
    build:
      context: ../
      dockerfile: ./src/Services/ProjectService/Dockerfile
    container_name: projectservice
    ports:
      - "5003:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Host=projectdb;Database=project_db;Username=postgres;Password=postgres;
    networks:
      - gateway_network

  commentsservice:
    build:
      context: ../
      dockerfile: ./src/Services/CommentsService/Dockerfile
    container_name: commentsservice
    ports:
      - "5004:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDBSettings__Connection=mongodb://admin:password@commentsdb:27017/
      - MongoDBSettings__DatabaseName=CommentsServiceDB
    networks:
      - gateway_network

  fileservice:
    build:
      context: ../
      dockerfile: ./src/Services/FileService/Dockerfile
    container_name: fileservice
    ports:
      - "5005:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - AppSettings__ConnectionString=Host=filesdb;Port=filedb;Database=files_db;Username=postgres;Password=postgres;
      - AppSettings__FileStorage=FileStorage
      - AppSettings__UseBaseDir=true
    networks:
      - gateway_network
