# Build and Publish Docker Images
name: CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v3
        with:
          submodules: recursive # Инициализируем и обновляем submodules

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Gateway
      - name: Build and push Gateway Service
        uses: docker/build-push-action@v4
        with:
          context: ./src/Gateway
          file: ./src/Gateway/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/gatewayservice:latest

      # User Service
      - name: Build and push UserService
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./src/Services/UserService/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/userservice:latest

      # Project Service
      - name: Build and push ProjectService
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./src/Services/ProjectService/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/projectservice:latest

      # Comments Service
      - name: Build and push CommentsService
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./src/Services/CommentsService/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/commentsservice:latest

      # Frontend
      - name: Build and push Frontend
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./frontend/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/frontend:latest
